apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipelinerun
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/Babarnawaz123/tax-calculator-project.git"
  workspaces:
    - name: pipeline-workspace
      emptyDir: {}
